<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN DialogBoxes
QApplicationBase::$ClassFile['qpromptdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QPromptDialog.class.php';
QApplicationBase::$ClassFile['qtextboxpromptdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QTextBoxPromptDialog.class.php';
QApplicationBase::$ClassFile['qradiobuttonpromptdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QRadioButtonPromptDialog.class.php';
QApplicationBase::$ClassFile['qconfirmationdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QConfirmationDialog.class.php';
//// END DialogBoxes

//// BEGIN QAutoCompleteTextBox
QApplicationBase::$ClassFile['qautocompletetextboxbase'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QAutoCompleteTextBoxBase.class.php';
QApplicationBase::$ClassFile['qajaxautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QAjaxAutoCompleteTextBox.class.php';
QApplicationBase::$ClassFile['qjavascriptautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QJavaScriptAutoCompleteTextBox.class.php';
//// END QAutoCompleteTextBox

//// BEGIN QEmailTextBox
QApplicationBase::$ClassFile['qemailtextbox'] = __PLUGINS__ . '/QEmailTextBox/includes/QEmailTextBox.class.php';
//// END QEmailTextBox

//// BEGIN QFirebug
QApplicationBase::$ClassFile['qfirebug'] = __PLUGINS__ . '/QFirebug/includes/QFirebug.class.php';
//// END QFirebug

//// BEGIN QFlot
QApplicationBase::$ClassFile['qflot'] = __PLUGINS__ . '/QFlot/includes/QFlot.class.php';
QApplicationBase::$ClassFile['qflotseries'] = __PLUGINS__ . '/QFlot/includes/QFlotSeries.class.php';
//// END QFlot

?>