<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN DialogBoxes
Examples::AddPluginExampleFile('DialogBoxes', 'example/more_dialog_boxes.php * Pre-built Dialog Boxes: Confirmations and Prompts');
//// END DialogBoxes

//// BEGIN QAutoCompleteTextBox
Examples::AddPluginExampleFile('QAutoCompleteTextBox', 'example/autocomplete.php * Auto-complete Textbox Example');
//// END QAutoCompleteTextBox

//// BEGIN QEmailTextBox
Examples::AddPluginExampleFile('QEmailTextBox', 'example/emailtextbox.php QEmailTextBox: Validate Email Addresses');
//// END QEmailTextBox

//// BEGIN QFirebug
Examples::AddPluginExampleFile('QFirebug', 'example/qfirebug.php Introduction to Debugging with QFirebug');
//// END QFirebug

//// BEGIN QFlot
Examples::AddPluginExampleFile('QFlot', 'example/qflot-bar.php QFlot: Display a bar chart');
Examples::AddPluginExampleFile('QFlot', 'example/qflot-timeseries.php QFlot: Display a time series chart');
//// END QFlot

?>
