<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QFirebug
Examples::AddPluginExampleFile('QFirebug', 'example/qfirebug.php Introduction to Debugging with QFirebug');
//// END QFirebug

//// BEGIN QFlot
Examples::AddPluginExampleFile('QFlot', 'example/qflot-bar.php QFlot: Display a bar chart');
Examples::AddPluginExampleFile('QFlot', 'example/qflot-timeseries.php QFlot: Display a time series chart');
//// END QFlot

?>
