<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QFirebug
QApplicationBase::$ClassFile['qfirebug'] = __PLUGINS__ . '/QFirebug/includes/QFirebug.class.php';
//// END QFirebug

//// BEGIN QFlot
QApplicationBase::$ClassFile['qflot'] = __PLUGINS__ . '/QFlot/includes/QFlot.class.php';
QApplicationBase::$ClassFile['qflotseries'] = __PLUGINS__ . '/QFlot/includes/QFlotSeries.class.php';
//// END QFlot

?>